CREATE OR REPLACE FUNCTION get_first_image_alphabetically(p_ubytovani_id UBYTOVANI.UBYTOVANI_ID%TYPE)
RETURN OBRAZKY_UBYTOVANI.OBRAZEK%TYPE IS
  v_image OBRAZKY_UBYTOVANI.OBRAZEK%TYPE;
BEGIN
  SELECT OBRAZEK INTO v_image
  FROM OBRAZKY_UBYTOVANI
  WHERE UBYTOVANI_ID = p_ubytovani_id
  AND NAZEV = (
    SELECT MIN(NAZEV)
    FROM OBRAZKY_UBYTOVANI
    WHERE UBYTOVANI_ID = p_ubytovani_id
  )
  AND ROWNUM = 1;

  RETURN v_image;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL;
  WHEN TOO_MANY_ROWS THEN
    RETURN NULL;
  WHEN OTHERS THEN
    RAISE;
END get_first_image_alphabetically;
/

CREATE OR REPLACE FUNCTION hash_hesla (p_input VARCHAR2)
  RETURN VARCHAR2 IS
    l_result VARCHAR2(4000);
BEGIN
    SELECT STANDARD_HASH(p_input, 'SHA256') INTO l_result FROM DUAL;
    RETURN l_result;
END;
/
