CREATE OR REPLACE FUNCTION get_first_image_alphabetically(p_ubytovani_id UBYTOVANI.UBYTOVANI_ID%TYPE)
RETURN OBRAZKY_UBYTOVANI.OBRAZKY_UBYTOVANI_ID%TYPE IS
  v_image_id OBRAZKY_UBYTOVANI.OBRAZKY_UBYTOVANI_ID%TYPE;
BEGIN
  SELECT OBRAZKY_UBYTOVANI_ID INTO v_image_id
  FROM (
    SELECT OBRAZKY_UBYTOVANI_ID
    FROM OBRAZKY_UBYTOVANI
    WHERE UBYTOVANI_ID = p_ubytovani_id
    ORDER BY NAZEV
  )
  WHERE ROWNUM = 1;

  RETURN v_image_id;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL;
  WHEN OTHERS THEN
    RAISE;
END get_first_image_alphabetically;
/

CREATE OR REPLACE FUNCTION hash_hesla (p_input VARCHAR2)
  RETURN VARCHAR2 IS
    l_result VARCHAR2(4000);
BEGIN
    SELECT STANDARD_HASH(p_input, 'SHA256') INTO l_result FROM DUAL;
    RETURN l_result;
END;
/

CREATE OR REPLACE PACKAGE pck_utils AS

